language: node_js
node_js:
 - "7.0"
before_install:
 - "npm install -g typescript@2.0.10"
install:
 - "npm install && sed -i.bak 's/\"watch\": true/\"watch\": false/' tsconfig.json && tsc -p ."
script:
 - "npm test"
env:
 - TRAVIS=true
branches:
  only:
    - master
    - dev