language: node_js
node_js:
 - "7.0"
before_install:
 - "npm install -g typescript"
install:
 - "npm install && cat ./tsconfig.json | sed -i.bak 's/"watch": true/"watch": false/' tsconfig.json && tsc -p ."
script:
 - "npm test"
branches:
  only:
    - master
    - dev